[package]
name = "dragonvnc-codec"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dragonvnc-proto = { path = "../dragonvnc-proto" }
dragonvnc-capture = { path = "../dragonvnc-capture" }
anyhow.workspace = true
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ffmpeg-sys-next = "9"
libc = "0.2"

[dev-dependencies]
tokio.workspace = true
